"use client"

import { useState } from "react"
import { ArrowDownLeft, ArrowUpRight, BarChart3, Bell, Bitcoin, ChevronDown, CircleDollarSign, Clock3, CreditCard, LayoutDashboard, Menu, MoreHorizontal, Moon, Settings, ShieldCheck, Sparkles, Wallet, X } from "lucide-react"

const navItems = [
  { label: "Dashboard", icon: LayoutDashboard },
  { label: "Buy Crypto", icon: ArrowDownLeft },
  { label: "Sell Crypto", icon: ArrowUpRight },
  { label: "Transactions", icon: CreditCard },
  { label: "Analytics", icon: BarChart3 },
]

const assets = [
  { symbol: "ETH", name: "Ethereum", amount: "2.48 ETH", value: "$8,420.16", change: "+4.82%", tone: "violet", icon: Sparkles },
  { symbol: "USDC", name: "USD Coin", amount: "4,250.00 USDC", value: "$4,250.00", change: "+0.01%", tone: "blue", icon: CircleDollarSign },
  { symbol: "BTC", name: "Bitcoin", amount: "0.037 BTC", value: "$2,780.44", change: "+2.14%", tone: "orange", icon: Bitcoin },
]

const transactions = [
  { type: "Received", asset: "Ethereum", amount: "+0.82 ETH", fiat: "+$2,784.20", date: "Today, 10:24 AM", status: "Completed", icon: ArrowDownLeft, tone: "success" },
  { type: "Sent", asset: "USD Coin", amount: "-500.00 USDC", fiat: "-$500.00", date: "Yesterday, 4:18 PM", status: "Completed", icon: ArrowUpRight, tone: "muted" },
  { type: "Swap", asset: "BTC → ETH", amount: "0.012 BTC", fiat: "$902.40", date: "Aug 24, 11:07 AM", status: "Pending", icon: ArrowDownLeft, tone: "warning" },
  { type: "Received", asset: "Bitcoin", amount: "+0.025 BTC", fiat: "+$1,876.50", date: "Aug 21, 9:42 AM", status: "Completed", icon: ArrowDownLeft, tone: "success" },
]

export default function Dashboard() {
  const [active, setActive] = useState("Dashboard")
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [connected, setConnected] = useState(false)

  return (
    <main className="min-h-screen bg-background text-foreground">
      <aside className={`fixed inset-y-0 left-0 z-20 flex w-64 flex-col border-r border-border bg-sidebar px-5 py-6 transition-transform lg:translate-x-0 ${sidebarOpen ? "translate-x-0" : "-translate-x-full"}`}>
        <div className="flex items-center justify-between px-2">
          <div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground shadow-[0_0_24px_hsl(var(--primary)/.35)]"><ShieldCheck className="size-5" /></div><span className="font-mono text-lg font-bold tracking-[0.24em]">TOTALITY</span></div>
          <button className="text-muted-foreground lg:hidden" onClick={() => setSidebarOpen(false)} aria-label="Close menu"><X className="size-5" /></button>
        </div>
        <div className="mt-14 flex flex-col gap-2">
          <p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Overview</p>
          {navItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setSidebarOpen(false) }} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${active === label ? "bg-primary/15 text-primary" : "text-muted-foreground hover:bg-accent hover:text-foreground"}`}><Icon className="size-[18px]" />{label}</button>)}
        </div>
        <div className="mt-auto flex flex-col gap-2"><button onClick={() => setActive("Settings")} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${active === "Settings" ? "bg-primary/15 text-primary" : "text-muted-foreground hover:bg-accent hover:text-foreground"}`}><Settings className="size-[18px]" />Settings</button><div className="mt-4 rounded-2xl border border-border bg-card p-4"><div className="mb-3 flex items-center gap-2 text-xs text-muted-foreground"><Moon className="size-4" />Dark mode<span className="ml-auto size-2 rounded-full bg-primary" /></div><p className="text-xs leading-relaxed text-muted-foreground">Your portfolio, unified.</p></div></div>
      </aside>
      {sidebarOpen && <button aria-label="Close sidebar overlay" className="fixed inset-0 z-10 bg-background/70 lg:hidden" onClick={() => setSidebarOpen(false)} />}
      <section className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-border px-5 md:px-10"><div className="flex items-center gap-4"><button onClick={() => setSidebarOpen(true)} className="text-muted-foreground lg:hidden" aria-label="Open menu"><Menu /></button><div><p className="text-xs text-muted-foreground">Wednesday, August 28, 2024</p><h1 className="mt-1 text-xl font-semibold tracking-tight">Good morning, Alex</h1></div></div><div className="flex items-center gap-3"><button aria-label="Notifications" className="relative hidden rounded-xl border border-border p-2.5 text-muted-foreground hover:bg-accent sm:block"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary" /></button><button onClick={() => setConnected(!connected)} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-[0_8px_24px_hsl(var(--primary)/.2)] transition hover:brightness-110"><Wallet className="size-4" />{connected ? "0x71...A9F2" : "Connect wallet"}<ChevronDown className="hidden size-4 opacity-70 sm:block" /></button></div></header>
        {active === "Buy Crypto" ? <BuyCrypto /> : <div className="mx-auto max-w-[1440px] px-5 py-8 md:px-10 md:py-10"><div className="mb-8 flex items-end justify-between"><div><p className="mb-2 text-sm text-muted-foreground">Your total balance</p><div className="flex flex-wrap items-baseline gap-3"><h2 className="text-4xl font-semibold tracking-[-0.04em] md:text-5xl">$15,450.60</h2><span className="rounded-full bg-success/10 px-2.5 py-1 text-xs font-semibold text-success">+3.84%</span></div><p className="mt-2 text-sm text-muted-foreground">+$571.20 <span className="text-muted-foreground/70">in the last 24 hours</span></p></div><button className="hidden items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-medium text-muted-foreground hover:bg-accent sm:flex">Last 30 days <ChevronDown className="size-3.5" /></button></div>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total Balance" value="$15,450.60" detail="+$571.20 today" icon={Wallet} /><Stat label="24h Change" value="+3.84%" detail="Portfolio growth" icon={BarChart3} accent="success" /><Stat label="Assets Held" value="03" detail="Across 3 networks" icon={CircleDollarSign} /><Stat label="Pending Transactions" value="01" detail="Needs confirmation" icon={Clock3} accent="warning" /></div>
          <div className="mt-10 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Your portfolio</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">Assets</h3></div><button className="text-sm font-medium text-primary hover:underline">View all assets <span aria-hidden="true">→</span></button></div>
          <div className="mt-5 grid gap-4 md:grid-cols-3">{assets.map((asset) => <AssetCard key={asset.symbol} {...asset} />)}</div>
          <div className="mt-10 overflow-hidden rounded-2xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-5 py-5 md:px-6"><div><h3 className="font-semibold">Recent transactions</h3><p className="mt-1 text-sm text-muted-foreground">Your latest wallet activity</p></div><button className="text-sm font-medium text-primary hover:underline">View all <span aria-hidden="true">→</span></button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-border text-[10px] uppercase tracking-[0.14em] text-muted-foreground"><th className="px-6 py-4 font-medium">Transaction</th><th className="px-6 py-4 font-medium">Amount</th><th className="px-6 py-4 font-medium">Date</th><th className="px-6 py-4 font-medium">Status</th><th className="px-6 py-4" /></tr></thead><tbody>{transactions.map((tx) => <tr key={tx.date} className="border-b border-border/70 last:border-0 hover:bg-accent/40"><td className="px-6 py-4"><div className="flex items-center gap-3"><div className={`grid size-9 place-items-center rounded-xl ${tx.tone === "success" ? "bg-success/10 text-success" : tx.tone === "warning" ? "bg-warning/10 text-warning" : "bg-muted text-muted-foreground"}`}><tx.icon className="size-4" /></div><div><p className="text-sm font-medium">{tx.type}</p><p className="text-xs text-muted-foreground">{tx.asset}</p></div></div></td><td className="px-6 py-4"><p className="text-sm font-medium">{tx.amount}</p><p className="text-xs text-muted-foreground">{tx.fiat}</p></td><td className="px-6 py-4 text-sm text-muted-foreground">{tx.date}</td><td className="px-6 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${tx.status === "Completed" ? "bg-success/10 text-success" : "bg-warning/10 text-warning"}`}>{tx.status}</span></td><td className="px-6 py-4 text-right"><button aria-label={`More options for ${tx.type}`} className="rounded-lg p-2 text-muted-foreground hover:bg-accent"><MoreHorizontal className="size-4" /></button></td></tr>)}</tbody></table></div></div>
        </div>}</section>
    </main>
  )
}

function BuyCrypto() {
  const [asset, setAsset] = useState("ETH")
  const [amount, setAmount] = useState("1000")
  const [payment, setPayment] = useState("Visa •••• 4242")
  const [network, setNetwork] = useState("Ethereum")
  const [secure, setSecure] = useState(true)
  const fiatAmount = Number(amount) || 0
  const rates: Record<string, number> = { ETH: 3420.18, BTC: 68420.12, USDC: 1 }
  const received = fiatAmount / rates[asset]
  const fee = fiatAmount * 0.0125

  return <div className="mx-auto max-w-[1180px] px-5 py-8 md:px-10 md:py-10">
    <div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary">Buy crypto</p><h2 className="text-3xl font-semibold tracking-tight md:text-4xl">Fund your portfolio</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Purchase digital assets securely with your preferred payment method.</p></div>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]">
      <form className="rounded-2xl border border-border bg-card p-5 md:p-7" onSubmit={(event) => event.preventDefault()}>
        <div className="flex items-center justify-between border-b border-border pb-5"><div><h3 className="font-semibold">Purchase details</h3><p className="mt-1 text-sm text-muted-foreground">Choose what you want to add</p></div><div className="grid size-10 place-items-center rounded-xl bg-primary/15 text-primary"><Wallet className="size-5" /></div></div>
        <div className="mt-7 flex flex-col gap-6">
          <label className="flex flex-col gap-2"><span className="text-sm font-medium">Asset</span><div className="relative"><select aria-label="Select asset" value={asset} onChange={(event) => setAsset(event.target.value)} className="w-full appearance-none rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none transition focus:border-primary"><option value="ETH">Ethereum (ETH)</option><option value="BTC">Bitcoin (BTC)</option><option value="USDC">USD Coin (USDC)</option></select><ChevronDown className="pointer-events-none absolute right-4 top-3.5 size-4 text-muted-foreground" /></div></label>
          <label className="flex flex-col gap-2"><span className="text-sm font-medium">Amount</span><div className="flex items-center rounded-xl border border-border bg-background px-4 focus-within:border-primary"><span className="text-lg text-muted-foreground">$</span><input aria-label="Amount in USD" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value.replace(/[^0-9.]/g, ""))} className="min-w-0 flex-1 bg-transparent px-2 py-3 text-lg font-semibold outline-none" /><span className="text-xs font-medium text-muted-foreground">USD</span></div><span className="text-xs text-muted-foreground">Minimum purchase $10.00</span></label>
          <div className="grid gap-6 sm:grid-cols-2"><label className="flex flex-col gap-2"><span className="text-sm font-medium">Payment method</span><div className="relative"><select aria-label="Select payment method" value={payment} onChange={(event) => setPayment(event.target.value)} className="w-full appearance-none rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none focus:border-primary"><option>Visa •••• 4242</option><option>Apple Pay</option><option>Bank transfer</option></select><ChevronDown className="pointer-events-none absolute right-4 top-3.5 size-4 text-muted-foreground" /></div></label><label className="flex flex-col gap-2"><span className="text-sm font-medium">Network</span><div className="relative"><select aria-label="Select network" value={network} onChange={(event) => setNetwork(event.target.value)} className="w-full appearance-none rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none focus:border-primary"><option>Ethereum</option><option>Arbitrum</option><option>Base</option></select><ChevronDown className="pointer-events-none absolute right-4 top-3.5 size-4 text-muted-foreground" /></div></label></div>
          <button type="button" role="switch" aria-checked={secure} onClick={() => setSecure(!secure)} className="flex items-center justify-between rounded-xl border border-border bg-background p-4 text-left"><div className="flex items-center gap-3"><div className={`grid size-9 place-items-center rounded-lg ${secure ? "bg-success/10 text-success" : "bg-muted text-muted-foreground"}`}><ShieldCheck className="size-4" /></div><div><p className="text-sm font-medium">Use Secure Checkout</p><p className="mt-1 text-xs text-muted-foreground">Extra verification for every purchase</p></div></div><span className={`relative h-6 w-11 rounded-full transition ${secure ? "bg-primary" : "bg-muted"}`}><span className={`absolute top-1 size-4 rounded-full bg-primary-foreground transition ${secure ? "left-6" : "left-1"}`} /></span></button>
        </div>
      </form>
      <aside className="h-fit rounded-2xl border border-primary/25 bg-primary/5 p-5 md:p-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Order summary</p><div className="mt-6 flex items-center justify-between"><span className="text-sm text-muted-foreground">You pay</span><span className="text-lg font-semibold">${fiatAmount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span></div><div className="mt-4 flex items-center justify-between"><span className="text-sm text-muted-foreground">Estimated receive</span><span className="text-sm font-semibold">{received.toFixed(asset === "USDC" ? 2 : 6)} {asset}</span></div><div className="mt-4 flex items-center justify-between"><span className="text-sm text-muted-foreground">Network fee</span><span className="text-sm font-medium">${fee.toFixed(2)}</span></div><div className="my-6 border-t border-border" /><div className="flex items-start gap-3 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-success" />Your transaction is protected by encrypted checkout and network confirmation.</div><button type="button" className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3.5 text-sm font-semibold text-primary-foreground shadow-[0_8px_24px_hsl(var(--primary)/.2)] transition hover:brightness-110">Continue to checkout <ArrowDownLeft className="size-4 rotate-[-45deg]" /></button><p className="mt-4 text-center text-[11px] text-muted-foreground">Rate locked for 30 seconds</p></aside>
    </div>
  </div>
}

function Stat({ label, value, detail, icon: Icon, accent = "primary" }: { label: string; value: string; detail: string; icon: typeof Wallet; accent?: string }) { return <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon className={`size-4 ${accent === "success" ? "text-success" : accent === "warning" ? "text-warning" : "text-primary"}`} /></div><p className="mt-5 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div> }
function AssetCard({ symbol, name, amount, value, change, tone, icon: Icon }: (typeof assets)[number]) { return <div className="group rounded-2xl border border-border bg-card p-5 transition hover:-translate-y-0.5 hover:border-primary/40"><div className="flex items-start justify-between"><div className={`grid size-11 place-items-center rounded-2xl ${tone === "violet" ? "bg-primary/15 text-primary" : tone === "blue" ? "bg-info/15 text-info" : "bg-warning/15 text-warning"}`}><Icon className="size-5" /></div><button aria-label={`Open ${symbol} options`} className="text-muted-foreground opacity-0 transition group-hover:opacity-100"><MoreHorizontal className="size-5" /></button></div><div className="mt-6 flex items-end justify-between"><div><p className="font-semibold">{symbol}</p><p className="mt-1 text-xs text-muted-foreground">{name}</p></div><div className="text-right"><p className="text-sm font-semibold">{amount}</p><p className="mt-1 text-xs text-muted-foreground">{value}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">24h performance</span><span className="text-xs font-semibold text-success">{change}</span></div></div> }

